apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260507-135127-tb0b0ietzmpv-service
spec:
  selector:
    app: enterprise-system-20260507-135127-tb0b0ietzmpv
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
